# See https://setuptools.readthedocs.io/en/latest/build_meta.html

[build-system]
# Use setuptools >= 43 because it automatically includes pyproject.toml in source distribution
# Use setuptools >= 46.5 to use attr: package.__version__
# Use setuptools >= 61 for pyproject.toml support
# https://setuptools.readthedocs.io/en/latest/history.html#id284
requires = ["setuptools >= 61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ratarmount"
version = "0.15.2"
description = "Random Access Read-Only Tar Mount"
authors = [{name = "Maximilian Knespel", email = "mxmlnkn@github.de"}]
license = {text = "MIT"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Archiving",
    "Topic :: System :: Archiving :: Compression",
    "Topic :: System :: Filesystems",
    "Topic :: Utilities",
]
urls = {Homepage = "https://github.com/mxmlnkn/ratarmount"}
dependencies = [
    "ratarmountcore ~= 0.7.0",
    "indexed_gzip >= 1.6.3, < 2.0",
    'indexed_zstd >= 1.3.1, < 2.0; sys_platform=="darwin"',
    'indexed_zstd >= 1.2.2, < 2.0; platform_system!="Windows"',
    'dataclasses; python_version < "3.7.0"',
    "python-xz ~= 0.4.0",
    "rapidgzip >= 0.13.1",
    "rarfile ~= 4.0",
    "libarchive-c ~= 5.1, < 6.0",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.optional-dependencies]
full = [
    "PySquashfsImage == 0.9.0",
    "lz4 ~= 4.0.0",
    "python-lzo ~= 1.0",
    "zstandard ~= 0.22.0",
    "isal ~= 1.0",
]
bzip2 = []
gzip = []
rar = []
xz = []
zip = []
zstd = []
# For now, only optional (and installed in the AppImage) because it is unstable and depends on many other packages
# that do not even have up-to-date wheels, i.e., will fail to install if, e.g., gcc and liblzo2-dev are not installed.
squashfs = [
    "PySquashfsImage == 0.9.0",
    "lz4 ~= 4.0.0",
    "python-lzo ~= 1.0",
    "zstandard ~= 0.22.0",
    "isal ~= 1.0",
]

[project.scripts]
ratarmount = "ratarmount:cli"

[tool.setuptools]
py-modules = ["ratarmount"]
license-files = ["LICENSE"]
